# Experiment 4 -- ModelSet Ecore classification, name encoded with worde4mde.
input:
  format: "ecore"
  metamodelpath: ""
  modelspath: "F:/Paper Preprocessing/Pre_Processing_Modeling_Artefacts_for_Graph_Neural_Networks__A_DSL_for_Model_Encoding/Codes/MoEGL-v2/experiments/data/modelset_ecore/models"
output:
  format: "NetworkX"
adaptations:
  metamodels:
    packages:
      ecore:
        uri:
          http://www.eclipse.org/emf/2002/Ecore:
            classes:
              include: ["EClassifier", "EStructuralFeature", "EPackage", "EEnumLiteral"]
              includeAllAttributes: false
              ENamedElement:
                features:
                  name:
                    encoding: "worde4mde"
              EPackage:
                include: ["eClassifiers", "name"]
              EClassifier:
                include: ["ePackage", "name"]
              EClass:
                include: ["ePackage", "eStructuralFeatures", "eSuperTypes", "name"]
              EEnum:
                include: ["ePackage", "eLiterals", "name"]
              EEnumLiteral:
                include: ["eEnum", "name"]
              EStructuralFeature:
                include: ["eContainingClass", "eType", "name"]
              EReference:
                include: ["eContainingClass", "eType", "eOpposite", "name"]
              EAttribute:
                include: ["eContainingClass", "eType", "name"]
              EDataType:
                include: ["ePackage", "name"]
